baseURL = "https://shanxitrip.me/"
title = "Shanxi Trip 山西旅游"
theme = "hextra"

[params]
  # 让顶部导航栏在滚动时吸顶
  navbar.displayTitle = true

# 顶部导航栏分类
[[menu.main]]
  name = "Landscape"
  pageRef = "/landscape"
  weight = 10
[[menu.main]]
  name = "Architecture"
  pageRef = "/architecture"
  weight = 20
[[menu.main]]
  name = "Religion"
  pageRef = "/religion"
  weight = 30
[[menu.main]]
  name = "Culture"
  pageRef = "/culture"
  weight = 40
[[menu.main]]
  name = "Food"
  pageRef = "/food"
  weight = 50
[[menu.main]]
  name = "Journeys"
  pageRef = "/journeys"
  weight = 60
[[menu.main]]
  name = "About Me"
  pageRef = "/about"
  weight = 70
